/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FolderBackupUI.java
 *
 * Created on May 18, 2012, 1:24:46 PM
 */
package folderautobackuputility;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author Sweord
 */
public class FolderBackupUI extends javax.swing.JFrame {

    final static long serialVersionUID = 124891l;
    static String FOLDER_CONFIG = "folders.cfg";
    File folderConfigFile = null;

    /** Creates new form FolderBackupUI */
    public FolderBackupUI() {
        initComponents();

        try {
            folderConfigFile = new File(FOLDER_CONFIG);
            if (folderConfigFile.canRead() != true) {
                folderConfigFile.createNewFile();

            }
            
        } catch (Exception ex) {
            Logger.getLogger(FolderBackupUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        folderList = new javax.swing.JList();
        ShowFolderButton = new javax.swing.JButton();
        AddFolderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        jScrollPane1.setViewportView(folderList);

        ShowFolderButton.setBackground(new java.awt.Color(153, 153, 255));
        ShowFolderButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        ShowFolderButton.setText("Show Folder Status");
        ShowFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowFolderButtonActionPerformed(evt);
            }
        });

        AddFolderButton.setBackground(new java.awt.Color(153, 153, 255));
        AddFolderButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        AddFolderButton.setText("Add Folder");
        AddFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFolderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowFolderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(AddFolderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ShowFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(AddFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFolderButtonActionPerformed
        // TODO add your handling code here:
        if (VernaFolderList == null) {
            VernaFolderList = new DefaultListModel();
        }
        JFileChooser rawr = new JFileChooser();
        rawr.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        rawr.showDialog(this, "Open");

        VernaFolder folderToAdd = null;
        folderToAdd = new VernaFolder(rawr.getSelectedFile());

        if (folderToAdd != null) {
            folderToAdd.reloadFileSet();
            VernaFolderList.addElement(folderToAdd);
        }
        folderList.setModel(VernaFolderList);

    }//GEN-LAST:event_AddFolderButtonActionPerformed

    private void ShowFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowFolderButtonActionPerformed
        // TODO add your handling code here:
        VernaFolder folderInQuestion = (VernaFolder) folderList.getSelectedValue();
        FolderBackupStatus statusScreen = new FolderBackupStatus(folderInQuestion);
        statusScreen.setVisible(true);
    }//GEN-LAST:event_ShowFolderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FolderBackupUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFolderButton;
    private javax.swing.JButton ShowFolderButton;
    private javax.swing.JList folderList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel VernaFolderList;
}
