/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FolderBackupInfo.java
 *
 * Created on May 18, 2012, 1:26:36 PM
 */
package folderautobackuputility;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;

/**
 * A small dialog showing the current backup status of a folder.
 *
 * @author Sweord
 */
public class FolderBackupInfo extends javax.swing.JFrame {

    /**
     * Creates new form FolderBackupInfo
     */
    public FolderBackupInfo() {
        initComponents();
    }

    /** 
     * Constructor that opens the window with information about the passed folder.
     * @param aFolder The folder to display information about.
     */
    public FolderBackupInfo(VernaFolder aFolder) {
        initComponents();
        this.setTitle(aFolder.getFolderName() + " backup information.");
        theFolder = aFolder;
        if (theFolder != null) {
            jLabel1.setText(theFolder.getFolderName());
        }
    }
    
    /**
     * Changes to a different folder.
     * @param aFolder 
     */
    public void setFolder(VernaFolder aFolder){
        this.setTitle(aFolder.getFolderName() + " backup information.");
        theFolder = aFolder;
        if (theFolder != null) {
            jLabel1.setText(theFolder.getFolderName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Populating Tree");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:


        if (theFolder != null) {
            theFoldersTree = new FolderTree(theFolder);
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(FolderBackupInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
            jTree1.setModel(theFoldersTree.FolderTreeModel);

        } else {
            TreeNode blank = new DefaultMutableTreeNode("No Folder Given!");
            
            jTree1.setModel(new DefaultTreeModel(blank));
            jLabel1.setText("No Folder");
        }
        




        System.out.println("Window Opened!");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FolderBackupInfo().setVisible(true);
            }
        });
    }
    
     //<editor-fold defaultstate="collapsed" desc="Variable Declarations">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    
    private VernaFolder theFolder = null;
    private SortedListModel FileListModel;
    FolderTree theFoldersTree;
    //</editor-fold>
    
}
